-- Keep an immutable, versioned record whenever an authenticated user accepts
-- the Terms of Use. The timestamp is generated by Postgres, not supplied by
-- the client, so it can be used as reliable audit evidence.

create table if not exists public.terms_acceptances (
  user_id uuid not null references auth.users (id) on delete cascade,
  terms_version text not null,
  accepted_at timestamptz not null default now(),
  primary key (user_id, terms_version),
  constraint terms_acceptances_version_not_blank
    check (char_length(btrim(terms_version)) between 1 and 64)
);

alter table public.terms_acceptances enable row level security;

revoke all on table public.terms_acceptances from anon, authenticated;
grant select on table public.terms_acceptances to authenticated;
grant insert (user_id, terms_version)
  on table public.terms_acceptances to authenticated;

drop policy if exists "Users can read own terms acceptances"
  on public.terms_acceptances;
create policy "Users can read own terms acceptances"
  on public.terms_acceptances
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can record own terms acceptances"
  on public.terms_acceptances;
create policy "Users can record own terms acceptances"
  on public.terms_acceptances
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- The RPC derives the user and leaves accepted_at to its database default.
-- Authenticated users only receive INSERT on these two columns, so they cannot
-- supply or alter the server-generated timestamp. Repeat calls are idempotent.
create or replace function public.record_terms_acceptance(
  p_terms_version text
)
returns timestamptz
language plpgsql
security invoker
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  normalized_version text := btrim(p_terms_version);
  recorded_at timestamptz;
begin
  if caller_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  if char_length(normalized_version) not between 1 and 64 then
    raise exception 'Terms version must contain between 1 and 64 characters.'
      using errcode = '22023';
  end if;

  insert into public.terms_acceptances (user_id, terms_version)
  values (caller_id, normalized_version)
  on conflict (user_id, terms_version) do nothing;

  select acceptance.accepted_at
    into recorded_at
    from public.terms_acceptances as acceptance
   where acceptance.user_id = caller_id
     and acceptance.terms_version = normalized_version;

  return recorded_at;
end;
$$;

revoke all on function public.record_terms_acceptance(text) from public;
revoke all on function public.record_terms_acceptance(text) from anon;
grant execute on function public.record_terms_acceptance(text)
  to authenticated, service_role;
